---
- name: setup
  hosts: localhost
  tasks:
    - name: Update homebrew
      community.general.homebrew:
        update_homebrew: true

    - name: Install common tools with brew
      community.general.homebrew:
        name: "{{ item }}"
        state: latest
      with_items:
        - ansible
        - curl
        - gh
        - golang
        - helm
        - htop
        - jq
        - kind
        - kubectx
        - kubernetes-cli
        - minikube
        - node
        - packer
        - pulumi
        - python
        - terraform
        - tfsec
        - tree
        - unzip
        - vim
        - watch
        - wget
        - yq
        - zsh

    - name: Install common tools with brew cask
      community.general.homebrew_cask:
        name: "{{ item }}"
        state: present
      with_items:
        - docker
        - google-chrome
        - google-cloud-sdk
        - iterm2
        - microsoft-remote-desktop
        - notion
        - postman
        - spotify
        - tableplus
        - tunnelblick
        - visual-studio-code

    - name: Install personal tools with brew cask
      when: work == "false"
      community.general.homebrew_cask:
        name: "{{ item }}"
        state: present
      with_items:
        - enpass
        - google-drive
        - mimestream
        - now-tv-player
        - telegram
        - whatsapp
        - zwift

    - name: Install work tools with brew cask
      when: work == "true"
      community.general.homebrew_cask:
        name: "{{ item }}"
        state: present
      with_items:
        - discord
        - keepassxc

    - name: Change python to python3
      replace:
        path: /Applications/Visual Studio Code.app/Contents/Resources/app/bin/code
        regexp: 'python(3)?'
        replace: 'python3'

    - name: Check if .oh-my-zsh exists
      stat:
        path: /Users/{{ lookup('env', 'USER') }}/.oh-my-zsh
      register: is_oh_my_zsh_present

    - name: Cloning oh-my-zsh
      git:
        repo: https://github.com/ohmyzsh/ohmyzsh.git
        dest: /Users/{{ lookup('env', 'USER') }}/.oh-my-zsh
      when: not is_oh_my_zsh_present.stat.exists

    - name: Set zshrc
      template:
        src: ./files/zshrc
        dest: /Users/{{ lookup('env', 'USER') }}/.zshrc
        owner: "{{ lookup('env', 'USER') }}"
        force: true

    - name: Change user shell to zsh
      user:
        name: "{{ lookup('env', 'USER') }}"
        shell: /usr/local/bin/zsh

    - name: Install VSCode themes
      command: code --install-extension {{ item }}
      with_items:
        - whizkydee.material-palenight-theme
        - eliverlara.andromeda
        - tal7aouy.icons

    - name: Install VSCode extensions
      command: code --install-extension {{ item }}
      with_items:
        - redhat.vscode-yaml
        - hashicorp.terraform
        - 4ops.packer
        - golang.go
        - ms-azuretools.vscode-docker
        - ms-python.python

    - name: Prepare repo folder
      file:
        path: /Users/{{ lookup('env', 'USER') }}/Documents/repo
        state: directory

    - name: Removing default dock icons
      command: dockutil --remove all

    - name: Set personal dock icons
      command: dockutil --add {{ item }}
      when: work == "false"
      with_items:
        - /Applications/Google\ Chrome.app
        - /Applications/Visual\ Studio\ Code.app
        - /Applications/iTerm.app
        - /Applications/Postman.app
        - /Applications/Microsoft\ Remote\ Desktop.app
        - /Applications/Notion.app
        - /Applications/Spotify.app
        - /Applications/Mimestream.app
        - /Applications/WhatsApp.app
        - /Applications/Telegram.app
      loop_control:
        pause: 10

    - name: Set work dock icons
      command: dockutil --add {{ item }}
      when: work == "true"
      with_items:
        - /Applications/Google\ Chrome.app
        - /Applications/Visual\ Studio\ Code.app
        - /Applications/iTerm.app
        - /Applications/Postman.app
        - /Applications/Microsoft\ Remote\ Desktop.app
        - /Applications/Notion.app
        - /Applications/Spotify.app
        - /Applications/KeePassXC.app
        - /System/Applications/Mail.app
      loop_control:
        pause: 10
