---
- name: Mac setup
  hosts: localhost

  tasks:
    - name: Install tools with brew
      community.general.homebrew:
        name: "{{ item }}"
        state: latest
        update_homebrew: yes
      with_items:
        - ansible
        - curl
        - gh
        - golang
        - htop
        - kind
        - kubernetes-cli
        - kubernetes-helm
        - terraform
        - unzip
        - vim
        - zsh

    - name: Install tools with brew cask
      community.general.homebrew_cask:
        name: "{{ item }}"
        state: present
        update_homebrew: yes
      with_items:
        - adobe-acrobat-reader
        - docker
        - enpass
        - firefox
        - github
        - google-chrome
        - google-drive
        - microsoft-remote-desktop
        - notion
        - postman
        - spotify
        - telegram
        - visual-studio-code
        - whatsapp

    - name: Install oh-my-zsh
      command: sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
      args:
        creates: "/Users/{{ lookup('env', 'USER') }}/.oh-my-zsh"
