---
- name: Mac setup
  hosts: localhost

  tasks:
    - name: check if present
      file:
        path: /Users/giacomofurlan/Documents/repo/namegenerator.sh
        state: present
    
    - name: install brew
      command: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
