---
- name: Mac setup
  hosts: localhost

  tasks:
    - name: Install tools with brew
      community.general.homebrew:
        name: "{{ item }}"
        state: latest
        update_homebrew: yes
      with_items:
        - ansible
        - curl
        - gh
        - golang
        - htop
        - kind
        - kubernetes-cli
        - kubernetes-helm
        - python
        - terraform
        - unzip
        - vim
        - zsh

    - name: Install tools with brew cask
      community.general.homebrew_cask:
        name: "{{ item }}"
        state: present
        update_homebrew: yes
      with_items:
        - adobe-acrobat-reader
        - docker
        - enpass
        - firefox
        - github
        - google-chrome
        - google-drive
        - microsoft-remote-desktop
        - notion
        - postman
        - spotify
        - telegram
        - visual-studio-code
        - whatsapp

    - name: check code file 
      copy:
        src: ./code
        dest: /Applications/Visual Studio Code.app/Contents/Resources/app/bin/code
        owner: giacomofurlan
        group: admin        
        mode: 0755

    - name: Install oh-my-zsh
      command: sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
      args:
        creates: "/Users/{{ lookup('env', 'USER') }}/.oh-my-zsh"

    - name: Install VSCode extensions
      shell: code --install-extension {{ item }}
      with_items:
        - redhat.vscode-yaml
        - whizkydee.material-palenight-theme
        - hashicorp.terraform
        - golang.go
        - ms-azuretools.vscode-docker
