---
- name: Mac setup
  hosts: localhost
  tasks:
    - name: Install tools with brew
      become_user: root
      community.general.homebrew:
        name: "{{ item }}"
        state: latest
        update_homebrew: true
      with_items:
        - ansible
        - curl
        - dockutil
        - gh
        - golang
        - htop
        - jq
        - kind
        - kubernetes-cli
        - kubernetes-helm
        - pulumi
        - python
        - terraform
        - tfsec
        - unzip
        - vim
        - watch
        - zsh

    - name: Install tools with brew cask
      become_user: root
      community.general.homebrew_cask:
        name: "{{ item }}"
        state: present
        update_homebrew: true
      with_items:
        - adobe-acrobat-reader
        - docker
        - discord
        - enpass
        - firefox
        - google-chrome
        - google-cloud-sdk
        - google-drive
        - microsoft-remote-desktop
        - microsoft-teams
        - notion
        - postman
        - spotify
        - telegram
        - tfsec
        - visual-studio-code
        - whatsapp
        - zwift

    - name: Check code file
      copy:
        src: ./files/code
        dest: /Applications/Visual Studio Code.app/Contents/Resources/app/bin/code

    - name: Check if .oh-my-zsh exists
      stat:
        path: /Users/{{ lookup('env', 'USER') }}/.oh-my-zsh
      register: is_oh_my_zsh_present

    - name: Cloning oh-my-zsh
      git:
        repo: https://github.com/ohmyzsh/ohmyzsh.git
        dest: /Users/{{ lookup('env', 'USER') }}/.oh-my-zsh
      when: not is_oh_my_zsh_present.stat.exists

    - name: Set zshrc
      template:
        src: ./files/zshrc
        dest: /Users/{{ lookup('env', 'USER') }}/.zshrc
        owner: "{{ lookup('env', 'USER') }}"
        force: true

    - name: Change user shell to zsh
      become: true
      user:
        name: "{{ lookup('env', 'USER') }}"
        shell: /usr/local/bin/zsh

    - name: Install VSCode extensions
      command: code --install-extension {{ item }}
      with_items:
        - redhat.vscode-yaml
        - whizkydee.material-palenight-theme
        - hashicorp.terraform
        - golang.go
        - ms-azuretools.vscode-docker
        - ms-python.python

    - name: Prepare repo folder
      file:
        path: /Users/{{ lookup('env', 'USER') }}/Documents/repo
        state: directory

    - name: Removing default dock icons
      command: dockutil --remove all

    - name: Set new dock icons
      command: dockutil --add {{ item }}
      with_items:
        - /Applications/Google\ Chrome.app
        - /Applications/Firefox.app
        - /Applications/Visual\ Studio\ Code.app
        - /System/Applications/Utilities/Terminal.app
        - /Applications/Postman.app
        - /Applications/Microsoft\ Remote\ Desktop.app
        - /Applications/Notion.app
        - /Applications/Spotify.app
        - /System/Applications/Mail.app
        - /Applications/WhatsApp.app
        - /Applications/Telegram.app
        - /Applications/Discord.app
      loop_control:
        pause: 10
