---
name: yaml
on:
  - pull_request
jobs:
  yamllint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Install linter
        run: pip3 install --user yamllint
      - name: lint
        run: yamllint -f colored playbook.yml
