---
name: playbook
on:
  pull_request:
    branches:
      - main
jobs:
  ansible:
    strategy:
      matrix:
        vars:
          - default
          - work
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Run playbook
        run: make run-${{ matrix.vars }}-ci
