---
name: playbook
on:
  workflow_dispatch:
  pull_request:

jobs:
  ansible:
    runs-on: macos-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Run playbook
      run: cd bin && ./bootstrap
